
POSICION_LETRA = 0
POSICION_BOOL=1
INGRESO1 = 0
INGRESO2 = 1
INTENTOS= 0
ACIERTOS=1

# CONSTANTES DEL CSV:
POS_ACIERTOS_REGISTRO = 3
POS_INTENTOS_REGISTRO = 4
POS_NOMBRE_REGISTRO = 2

# PRE ARCHIVO DE CONFIG 
MAX_PARTIDAS = 2
