from config.Constantes_config import *

POSICION_LETRA = 0
POSICION_BOOL=1
INGRESO1 = 0
INGRESO2 = 1


# CONSTANTES DE INICIALIZACION
INICIAR_CANT_PARTIDAS = 1
MINIMO_JUGADORES = 2

# CONSTANTES DEL CSV:
POS_ACIERTOS_REGISTRO = 3
POS_INTENTOS_REGISTRO = 4
POS_NOMBRE_REGISTRO = 2

# CONSTANTES DE POSICION DE DICCIONARIO
INTENTOS= 0
ACIERTOS=1
PARTIDAS_JUGADAS = 2
